language: c

compiler:
  - i686-w64-mingw32-gcc
  - x86_64-w64-mingw32-gcc

addons:
  apt:
    packages:
      - gcc-mingw-w64
      - wine
      - cmake

env:
  - ci_buildsys=cmake
  - ci_buildsys=Makefile

script:
  - ci_target=${CC%-*} ./tools/ci-build.sh
